from src.models import Data, Parameter
from llm_sdk import  Small_LLM_Model
from typing import List, Dict
from src.decoder import Constrained_Decoder
import json


data = Data()
allowed_functions = [fn.name for fn in data.functions_definition]
model = Small_LLM_Model()
prompts: List[str] = data.prompts
decoder = Constrained_Decoder()
out_path = data.output_path
json_output = []

for i, prompt in enumerate(prompts):
    print(f"[{i + 1}/{len(prompts)}] processing...")

    # the picked function name
    chosen_function = decoder.select_function_name(prompt, data.functions_definition)

    # Generating function arguments only if a valid function is generated by the llm
    fn_map = {fn.name: fn for fn in data.functions_definition}
    if chosen_function in fn_map:
        chosen_function_obj = fn_map[chosen_function]
        arguments: Dict = decoder.select_arguments(prompt,chosen_function_obj)


    # Map back to the FunctionDef
    if chosen_function not in allowed_functions:
        print(f"Cannot generate function name : {data.prompts[i]}")
        chosen_function = ""

    print(f"{chosen_function}") #------------------------->

    json_output.append({
        "prompt": prompt,
        "name": chosen_function,
        "parameters": arguments
    })

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(json_output, f, indent=2)























