from src.models import Data, Parameter
from llm_sdk import  Small_LLM_Model
from typing import List, Dict
from src.decoder import Constrained_Decoder
from src.build_prompts import build_prompt_for_argument, build_function_selection_prompt


data = Data()
allowed_functions = [fn.name for fn in data.functions_definition]
model = Small_LLM_Model()
prompts: List[str] = data.prompts
decoder = Constrained_Decoder(Small_LLM_Model)

for i, prompt in enumerate(prompts):
    print(f"[{i + 1}/{len(data.prompts)}] processing...")
    arguments_d = data.functions_definition

    # prompt to make ids from
    structured_fun_prompt = build_function_selection_prompt(prompt, data.functions_definition)

    # the picked function name
    chosen_function = decoder.select_function(structured_fun_prompt, allowed_functions)

    # Generating function arguments only if a valid function is generated by the llm
    fn_map = {fn.name: fn for fn in data.functions_definition}
    if chosen_function in fn_map:
        chosen_function_obj = fn_map[chosen_function]
        arguments: Dict = decoder.select_arguments(prompt, chosen_function_obj)


    # Map back to the FunctionDef
    if chosen_function not in allowed_functions:
        print(f"Cannot generate function name : {data.prompts[i]}")
        chosen_function=""






    print(f"{chosen_function}") #------------------------->
    #data.data_output(chosen_function, )

    break






















